apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: brvast/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: 'src/**/*.js'
            src: .
    - image: brvast/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: '*.js'
            src: .
    - image: brvast/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: '*.js'
            src: .
    - image: brvast/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: '*.js'
            src: .
    - image: brvast/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: '*.js'
            src: .
    - image: brvast/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: '*.js'
            src: .

